apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aspire-app
  namespace: prod
spec:
  chart:
    spec:
      chart: aspire-app-chart
      sourceRef:
        kind: HelmRepository
        name: my-repo
        namespace: flux-system
      version: 0.1.0
  interval: 5m0s
  values:
    images:
      api: ghcr.io/my-org/api-service:1.3.9
      nginx: nginx:4.99.9
      redis: redis:1.40.0
      web: ghcr.io/my-org/web-app:1.7.99
    replicas:
      api: 2
      web: 2
