apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: my-app
  namespace: dev
spec:
  chart:
    spec:
      chart: my-chart
      sourceRef:
        kind: HelmRepository
        name: my-repo
        namespace: flux-system
      version: 1.0.0
  interval: 5m0s
  values:
    image:
      repository: ghcr.io/my-org/my-api
      tag: 1.3.8
    initContainers:
    - image:
        repository: busybox
        tag: 1.37.0
      name: setup
    nested:
      deeper:
        evenDeeper:
          image:
            repository: alpine
            tag: 3.20.0
    sidecar:
      image:
        repository: envoyproxy/envoy
        tag: 1.26.3
status: {}
