name: Test Action 

on:
  workflow_dispatch:
    
jobs:  
  test_helmrelease_action:
    name: Try GitHub-Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: test github hacktion
        uses: github-hacktions/flux-helm-bump@main
        with:
          file: test_files/multiple-bump.yaml
          set: | 
            ghcr.io/my-org/my-api=1.3.10
            busybox=1.38.2
            alpine=3.42.42

