name: Test Action 

on:
  workflow_dispatch:
    
jobs:  
  test_helmrelease_action:
    name: Try GitHub-Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: test github hacktion
        uses: github-hacktions/flux-helpers-action@main
        with:
          file: test_files/multiple-bump.yaml
          set: |
           ghcr.io/my-api=1.3.10
           busybox=1.38.2
          dry-run: true
